TIMEOUT 30
DEFAULT primary

MENU TITLE L4T boot options

LABEL primary
      MENU LABEL primary kernel
      LINUX /boot/Image
      INITRD /boot/initrd
      FDT /boot/dtb/kernel_tegra234-p3768-0000+p3767-0005-nv-super.dtb
      OVERLAYS /boot/framos/dtbo/tegra234-p3767-camera-p3768-fr_fpa_a_p22-overlay.dtbo,/boot/framos/dtbo/tegra234-p3767-camera-p3768-fr_imx900-cam1-4lane-overlay.dtbo,/boot/arducam/dtbo/tegra234-p3767-camera-ar_imx519-cam0-2lane-overlay.dtbo
      APPEND ${cbootargs} root=PARTUUID=ec267ee1-373a-406b-8dd8-fec76650f345 rw rootwait rootfstype=ext4 mminit_loglevel=4 console=ttyTCU0,115200 firmware_class.path=/etc/firmware fbcon=map:0 video=efifb:off console=tty0 nv-auto-config 

# When testing a custom kernel, it is recommended that you create a backup of
# the original kernel and add a new entry to this file so that the device can
# fallback to the original kernel. To do this:
#
# 1, Make a backup of the original kernel
#      sudo cp /boot/Image /boot/Image.backup
#
# 2, Copy your custom kernel into /boot/Image
#
# 3, Uncomment below menu setting lines for the original kernel
#
# 4, Reboot

LABEL backup
    MENU LABEL backup kernel
    LINUX /boot/Image.backup
    INITRD /boot/initrd
    APPEND ${cbootargs}

